-- MySQL Script generated by MySQL Workbench
-- Tue Oct 12 20:27:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema planetshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema planetshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `planetshop` DEFAULT CHARACTER SET utf8 ;
USE `planetshop` ;

-- -----------------------------------------------------
-- Table `planetshop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planetshop`.`categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planetshop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planetshop`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `id_category` INT NOT NULL,
  `price` INT NOT NULL,
  `image` VARCHAR(250) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `amount_in_stock` INT NOT NULL,
  `available` TINYINT NOT NULL DEFAULT 1,
  `inhabitants` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `categories_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `categories`
    FOREIGN KEY (`id_category`)
    REFERENCES `planetshop`.`categories` (`id_category`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planetshop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planetshop`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_surname` VARCHAR(45) NOT NULL,
  `user_date_of_birth` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `user_email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planetshop`.`user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planetshop`.`user_address` (
  `id_user_address` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `house` VARCHAR(45) NOT NULL,
  `flat` VARCHAR(45) NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_user_address`),
  INDEX `users_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `users`
    FOREIGN KEY (`id_user`)
    REFERENCES `planetshop`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planetshop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planetshop`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_user_address` INT NOT NULL,
  `order_status` VARCHAR(45) NOT NULL,
  `date_order` DATE NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `delivery_method` VARCHAR(45) NOT NULL,
  `order_price` INT NOT NULL,
  `payment_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `user_address_idx` (`id_user_address` ASC) VISIBLE,
  INDEX `users_idx` (`id_user` ASC) VISIBLE,
    FOREIGN KEY (`id_user_address`)
    REFERENCES `planetshop`.`user_address` (`id_user_address`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (`id_user`)
    REFERENCES `planetshop`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planetshop`.`product_in_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planetshop`.`product_in_order` (
  `id_product_in_order` INT NOT NULL AUTO_INCREMENT,
  `id_order` INT NOT NULL,
  `id_product` INT NOT NULL,
  `amount_in_order` INT NOT NULL,
  PRIMARY KEY (`id_product_in_order`),
  INDEX `products_idx` (`id_product` ASC) VISIBLE,
  INDEX `orders_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `products`
    FOREIGN KEY (`id_product`)
    REFERENCES `planetshop`.`products` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders`
    FOREIGN KEY (`id_order`)
    REFERENCES `planetshop`.`orders` (`id_order`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
